name: Packaging

# testing!
on: push
#on:
#  push:
#    branches:
#      - main

jobs:
  build:
    name: Build packages
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      -
        name: Setup Poetry
        run: python -m pip install poetry==1.1.4
      -
        name: Build project package
        run: poetry build
      -
        name: Store package artefacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-${{ runner.os }}
          path: dist

  test:
    name: Test packages
    needs: build
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Retrieve package artefacts
        uses: actions/download-artifact@v2
        with:
          name: dist-${{ runner.os }}
      -
        name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      -
        name: Upgrade Python Pip
        run: python -m pip install --upgrade pip
      -
        name: Test installing project package
        run: python -m pip install --find-links=. mapaction_rds_dashboard
