name: Release

on: release

jobs:
  build:
    name: 📦 Build
    runs-on: "ubuntu-latest"
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      -
        name: Upgrade Python Pip
        run: python -m pip install --upgrade pip
      -
        name: Setup Poetry
        run: python -m pip install poetry==1.1.4
      -
        name: Build project package
        run: poetry build
      -
        name: Store package artefacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  verify:
    name: 📋 Verify
    needs: build
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Retrieve package artefacts
        uses: actions/download-artifact@v2
        with:
          name: dist
      -
        name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      -
        name: Upgrade Python Pip
        run: python -m pip install --upgrade pip
      -
        name: Test installing project package
        run: python -m pip install --find-links=. mapy_rds_dashboard

  release:
    name: 🚚 Release
    needs: verify
    runs-on: "ubuntu-latest"
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Retrieve package artefacts
        uses: actions/download-artifact@v2
        with:
          name: dist
      -
        name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      -
        name: Upgrade Python Pip
        run: python -m pip install --upgrade pip
      -
        name: Setup Poetry
        run: python -m pip install poetry==1.1.4
      -
        name: Move packages
        run: |
          mkdir dist
          mv mapy_* dist/
      -
        name: Publish package to PyPi
        run: poetry publish --repository testpypi
        env:
          POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.POETRY_PYPI_TOKEN_TESTPYPI }}
