name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
        architecture: x64
    - run: pip install poetry==1.1.4
    - run: poetry install
    - run: poetry run flake8 src tests
    - run: poetry run mypy src
    - run: poetry pytest
    - run: poetry pytest --cov
    - run: poetry pytest --typeguard-packages mapaction_rds_dashboard
