name: Tests

on: push

jobs:
  test:
    name: 🧪 Tests
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      -
        name: Upgrade Python Pip
        run: python -m pip install --upgrade pip
      -
        name: Setup Poetry
        run: python -m pip install poetry==1.1.4
      -
        name: Setup project dependencies
        run: poetry install
      -
        name: Export project dependencies
        run: poetry export --dev --format=requirements.txt --without-hashes --output requirements.txt
      -
        name: Check project dependencies
        run: poetry run safety check --file requirements.txt
      -
        name: Run Flake8 linting
        run: poetry run flake8 src tests
      -
        name: Run MyPy type checks
        run: poetry run mypy src
      -
        name: Run test suite
        run: poetry run pytest
      -
        name: Check test suite coverage
        run: poetry run pytest --cov
        continue-on-error: true
      -
        name: Run TypeGuard type checks
        run: poetry run pytest --typeguard-packages mapy_rds_dashboard
